/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package R08_C8_Group2_Assignment2;

public class App {

    public static void main(String[] args) {

        SqlController.connectServer();
        SqlController.prepareForStatement();



        // #######################################################################################
        // parse json, import all card to database. "Credit Card" default username = root
        SqlController.importValidCard();
        // #######################################################################################
        UserInterface newInstance = new UserInterface();
        newInstance.mainMenu();

        SqlController.disconnectDataBase();
    }
}
