/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package R08_C8_Group2_Assignment2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
